version: "3.9"
services:
  udp-1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - udp-network

  udp-2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - udp-network
  udp-3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - udp-network

networks:
  udp-network: